# Generated by Django 4.2.4 on 2024-01-19 17:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tasks.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Task list name', max_length=32)),
                ('description', models.CharField(blank=True, help_text='Task list description', max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update')),
                ('user', models.ForeignKey(help_text='Task list owner', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, help_text='Task title', max_length=32)),
                ('description', models.CharField(blank=True, help_text='Task description', max_length=256, null=True)),
                ('is_completed', models.BooleanField(default=False, help_text='Designates if the task is completed')),
                ('is_starred', models.BooleanField(default=False, help_text='Designates if the task is important')),
                ('deadline', models.DateTimeField(blank=True, db_index=True, help_text='Task deadline', null=True, validators=[tasks.validators.validate_deadline])),
                ('completion_rate', models.PositiveSmallIntegerField(default=0, help_text='Task completion percentage', validators=[django.core.validators.MaxValueValidator(100, 'Ensure this value is less than or equal to 100'), django.core.validators.MinValueValidator(0, 'Ensure this value is greater than or equal to 0')])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update')),
                ('list', models.ForeignKey(help_text='Task list', on_delete=django.db.models.deletion.CASCADE, to='tasks.list')),
                ('user', models.ForeignKey(help_text='Task owner', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(check=models.Q(('completion_rate__gte', 0)), name='completion_rate_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(check=models.Q(('completion_rate__lte', 100)), name='completion_rate_lte_100'),
        ),
    ]
