# Generated by Django 4.2 on 2023-04-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='description',
            field=models.CharField(blank=True, help_text='Task list description', max_length=256, null=True),
        ),
    ]
