# Generated by Django 4.2.4 on 2024-01-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='description',
            field=models.CharField(default='', help_text='Task list description', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(default='', help_text='Task description', max_length=256),
            preserve_default=False,
        ),
    ]
