# Generated by Django 4.2 on 2023-05-15 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_list_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='default',
        ),
    ]
