# Generated by Django 4.2.4 on 2024-01-24 08:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_alter_list_description_alter_task_description'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task',
            name='completion_rate_gte_0',
        ),
        migrations.RemoveConstraint(
            model_name='task',
            name='completion_rate_lte_100',
        ),
        migrations.RemoveField(
            model_name='task',
            name='completion_rate',
        ),
        migrations.AddField(
            model_name='task',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0, help_text='Task completion progress', validators=[django.core.validators.MaxValueValidator(100, 'Ensure this value is less than or equal to 100'), django.core.validators.MinValueValidator(0, 'Ensure this value is greater than or equal to 0')]),
        ),
        migrations.AlterField(
            model_name='list',
            name='user',
            field=models.ForeignKey(help_text='Task list owner', on_delete=django.db.models.deletion.CASCADE, related_name='lists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='list',
            field=models.ForeignKey(help_text='Task list', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.list'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(help_text='Task owner', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(check=models.Q(('progress__gte', 0)), name='progress_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(check=models.Q(('progress__lte', 100)), name='progress_lte_100'),
        ),
    ]
