# Generated by Django 4.2.4 on 2024-02-08 07:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_task_completion_rate_gte_0_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'verbose_name': 'Task List', 'verbose_name_plural': 'Task Lists'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterField(
            model_name='task',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0, help_text='Task progress', validators=[django.core.validators.MaxValueValidator(100, 'Ensure this value is less than or equal to 100'), django.core.validators.MinValueValidator(0, 'Ensure this value is greater than or equal to 0')]),
        ),
    ]
