# Generated by Django 4.2 on 2023-05-28 17:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_list_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('id',)},
        ),
        migrations.RemoveField(
            model_name='task',
            name='due',
        ),
        migrations.AddField(
            model_name='task',
            name='completion_rate',
            field=models.PositiveSmallIntegerField(default=0, help_text='Task completion percentage', validators=[django.core.validators.MaxValueValidator(100, 'Ensure this value is less than or equal to 100.'), django.core.validators.MinValueValidator(0, 'Ensure this value is greater than or equal to 0.')]),
        ),
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text='Task deadline', null=True),
        ),
        migrations.AddIndex(
            model_name='list',
            index=models.Index(fields=['name'], name='list_name_index'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['title'], name='task_title_index'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(check=models.Q(('completion_rate__gte', 0)), name='completion_rate_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(check=models.Q(('completion_rate__lte', 100)), name='completion_rate_lte_100'),
        ),
        migrations.AlterModelTable(
            name='list',
            table=None,
        ),
        migrations.AlterModelTable(
            name='task',
            table=None,
        ),
    ]
