# Generated by Django 4.2.4 on 2023-08-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_list_list_name_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Task deadline', null=True),
        ),
    ]
