# Generated by Django 5.1 on 2024-10-05 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("comments", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                help_text="Comment owner",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
