# Generated by Django 5.1 on 2024-10-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="sub_tasks",
            field=models.ManyToManyField(
                help_text="Subtasks", related_name="subtasks", to="tasks.task"
            ),
        ),
    ]
