# Generated by Django 5.1 on 2024-10-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_alter_task_sub_tasks"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="attachment",
            field=models.FileField(
                blank=True, help_text="Attachment", null=True, upload_to="files/tasks/"
            ),
        ),
    ]
